#!/bin/bash

mkdir ~/EnacPack_temp 
cd ~/EnacPack_temp

# Installing Carbon Copy Cloner 
curl -L -o ccc.zip "https://bombich.com/software/download_ccc.php" -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.93 Safari/537.36" 
unzip ccc.zip 
mv "Carbon Copy Cloner.app" /Applications 
rm ccc.zip

