#!/bin/bash

mkdir ~/EnacPack_temp 
cd ~/EnacPack_temp

#Installing Chrome
curl -L -o "https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg" 
hdiutil mount -nobrowse googlechrome.dmg 
cp -R "/Volumes/Google Chrome/Google Chrome.app" /Applications
hdiutil unmount "/Volumes/Google Chrome" 
rm googlechrome.dmg

# Installing Firefox
curl -L -o Firefox.dmg "http://download.mozilla.org/?product=firefox-latest&os=osx&lang=en-US" 
hdiutil mount -nobrowse Firefox.dmg
cp -R "/Volumes/Firefox/Firefox.app" /Applications
hdiutil unmount "/Volumes/Firefox" 
rm Firefox.dmg

