#!/bin/bash

mkdir ~/EnacPack_temp
cd ~/EnacPack_temp

#Installing 



Chrome
curl -L -o "https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg" 
hdiutil mount -nobrowse googlechrome.dmg 
cp -R "/Volumes/Google Chrome/Google Chrome.app" /Applications
hdiutil unmount "/Volumes/Google Chrome" 
rm googlechrome.dmg

