#!/bin/bash

mkdir ~/EnacPack_temp 
cd ~/EnacPack_temp

#Installing Dropbox
curl -L -o Dropbox.dmg "https://www.dropbox.com/download?plat=mac&type=full"
hdiutil mount -nobrowse Dropbox.dmg 
cp -R "/Volumes/Dropbox Installer/Dropbox.app" /Applications
hdiutil unmount "/Volumes/Dropbox Installer" 
rm Dropbox.dmg

