#!/bin/bash

mkdir ~/EnacPack_temp 
cd ~/EnacPack_temp

# Installing Firefox 
curl -L -o Firefox.dmg "http://download.mozilla.org/?product=firefox-latest&os=osx&lang=en-US" 
hdiutil mount -nobrowse Firefox.dmg
cp -R "/Volumes/Firefox/Firefox.app" /Applications
hdiutil unmount "/Volumes/Firefox" 
rm Firefox.dmg

# Installing VLC Player 
curl -L -o vlc.dmg "http://get.videolan.org/vlc/2.2.4/macosx/vlc-2.2.4.dmg" 
hdiutil mount -nobrowse vlc.dmg -mountpoint / Volumes / vlc
cp -R "/Volumes/vlc/VLC.app" /Applications
hdiutil unmount "/Volumes/vlc" 
rm vlc.dmg

