#!/bin/bash

mkdir ~/EnacPack_temp
cd ~/EnacPack_temp

#Installing Firefox
curl -L -o Firefox.dmg "http://download.mozilla.org/?product=firefox-latest&os=osx&lang=en-US" 
hdiutil mount -nobrowse Firefox.dmg
cp -R "/Volumes/Firefox/Firefox.app" /Applications
hdiutil unmount "/Volumes/Firefox" 
rm Firefox.dmg

#Installing Skype
curl -L -o "http://www.skype.com/go/getskype-macosx.dmg"
hdiutil mount -nobrowse getskype-macosx.dmg 
cp -R "/Volumes/Skype/Skype.app" /Applications
hdiutil unmount "/Volumes/Skype"
rm getskype-macosx.dmg

#Installing Thunderbird
curl -L -o Thunderbird.dmg "https://download.mozilla.org/?product=thunderbird-52.0.1-SSL&os=osx&lang=en-US" 
hdiutil mount -nobrowse Thunderbird.dmg 
cp -R "/Volumes/Thunderbird/Thunderbird.app" /Applications 
hdiutil unmount "/Volumes/Thunderbird" 
rm Thunderbird.dmg

