#!/bin/bash

mkdir ~/EnacPack_temp 
cd ~/EnacPack_temp

#Installing Spotify
curl -L -o "http://download.spotify.com/Spotify.dmg"
hdiutil mount -nobrowse Spotify.dmg 
cp -R "/Volumes/Spotify/Spotify.app" /Applications
hdiutil unmount "/Volumes/Spotify"
rm Spotify.dmg

